

"""
Revision ID: a432de2089d5
Revises: None
Create Date: 2025-08-14 02:32:23.682726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a432de2089d5'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('diagram', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.Column('motive', sa.Integer(), nullable=True),
    sa.Column('opportunity', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('ease_of_discovery', sa.Integer(), nullable=True),
    sa.Column('ease_of_exploit', sa.Integer(), nullable=True),
    sa.Column('awareness', sa.Integer(), nullable=True),
    sa.Column('intrusion_detection', sa.Integer(), nullable=True),
    sa.Column('loss_of_confidentiality', sa.Integer(), nullable=True),
    sa.Column('loss_of_integrity', sa.Integer(), nullable=True),
    sa.Column('loss_of_availability', sa.Integer(), nullable=True),
    sa.Column('loss_of_accountability', sa.Integer(), nullable=True),
    sa.Column('financial_damage', sa.Integer(), nullable=True),
    sa.Column('reputation_damage', sa.Integer(), nullable=True),
    sa.Column('non_compliance', sa.Integer(), nullable=True),
    sa.Column('privacy_violation', sa.Integer(), nullable=True),
    sa.Column('residual_risk', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('threats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('information_system_id', sa.UUID(), nullable=True),
    sa.Column('remediation_id', sa.UUID(), nullable=True),
    sa.Column('risk_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['information_system_id'], ['information_systems.id'], ),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('use_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('information_system_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['information_system_id'], ['information_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_cases')
    op.drop_table('threats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('risks')
    op.drop_table('remediations')
    op.drop_table('information_systems')
    # ### end Alembic commands ###
