"""añade_campo_residual_risk

Revision ID: 05947fa10bba
Revises: 4a94543a3f82
Create Date: 2025-08-13 21:40:41.328210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05947fa10bba'
down_revision: Union[str, None] = '4a94543a3f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('information_systems', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('remediations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               nullable=False)
    op.alter_column('remediations', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('risks', sa.Column('residual_risk', sa.Float(), nullable=True))
    op.alter_column('risks', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('risks', 'discoverability')
    op.drop_column('risks', 'affected_users')
    op.drop_column('risks', 'reproducibility')
    op.drop_column('risks', 'exploitability')
    op.drop_column('risks', 'damage')
    op.drop_column('risks', 'compliance')
    op.alter_column('threats', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('threats', 'information_system_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('threats', 'remediation_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('threats', 'risk_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('use_cases', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('use_cases', 'information_system_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('use_cases', 'information_system_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('use_cases', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('threats', 'risk_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('threats', 'remediation_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('threats', 'information_system_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('threats', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.add_column('risks', sa.Column('compliance', sa.INTEGER(), nullable=True))
    op.add_column('risks', sa.Column('damage', sa.INTEGER(), nullable=True))
    op.add_column('risks', sa.Column('exploitability', sa.INTEGER(), nullable=True))
    op.add_column('risks', sa.Column('reproducibility', sa.INTEGER(), nullable=True))
    op.add_column('risks', sa.Column('affected_users', sa.INTEGER(), nullable=True))
    op.add_column('risks', sa.Column('discoverability', sa.INTEGER(), nullable=True))
    op.alter_column('risks', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('risks', 'residual_risk')
    op.alter_column('remediations', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('remediations', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('information_systems', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
