"""Añade campo compliance

Revision ID: 4a94543a3f82
Revises: 
Create Date: 2024-09-25 00:36:11.649847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a94543a3f82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('information_systems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('diagram', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remediations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('reproducibility', sa.Integer(), nullable=True),
    sa.Column('explotability', sa.Integer(), nullable=True),
    sa.Column('affected_users', sa.Integer(), nullable=True),
    sa.Column('discoverability', sa.Integer(), nullable=True),
    sa.Column('compliance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('information_system_id', sa.Integer(), nullable=True),
    sa.Column('remediation_id', sa.Integer(), nullable=True),
    sa.Column('risk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['information_system_id'], ['information_systems.id'], ),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediations.id'], ),
    sa.ForeignKeyConstraint(['risk_id'], ['risks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('use_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('information_system_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['information_system_id'], ['information_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('use_cases')
    op.drop_table('threats')
    op.drop_table('risks')
    op.drop_table('remediations')
    op.drop_table('information_systems')
    # ### end Alembic commands ###
