name: "CodeQL Advanced (api only)"

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "api/**"
  schedule:
    - cron: '17 5 * * 3'

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        include:
          - language: javascript-typescript
            build-mode: none
          - language: python
            build-mode: none
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


