name: Python API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  api-tests:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.event_name != 'schedule' }}
    name: API tests (pytest)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install pytest flake8
          [ -f api/requirements.txt ] && pip install -r api/requirements.txt || echo "No api/requirements.txt"

      - name: Lint (api)
        run: flake8 api --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run pytest (api/tests)
        working-directory: api
        env:
          PYTHONPATH: .
        run: pytest tests/
