# This workflow will install Python dependencies, run tests and lint within the api folder

name: Python application (api only)

on:
  push:
    branches: [ "main" ]
    paths:
      - "api/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "api/**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f api/requirements.txt ]; then pip insta
